### PR TITLE
[MRG] fixes the tort error, not sure if this needs a new test

### PR DESCRIPTION
**Pull request by alexrockhill**
Addresses https://github.com/pactools/pactools/issues/26

### CODE REVIEW

**Comment by alexrockhill** [comment]
I realized I should be a bit more verbose: the issue was an edge-case where the low-frequency signal `low_filtered[i]` equalled exactly π because the data was simulated. This made it so that it was assigned a new bin using np.digitize because it was not less than the top bin (it was equal). By reassigning right edge-case bins afterward this fixes the issue for the right edge while keeping the left edge-case working.

**Comment by TomDLT** [comment]
Thanks for the fix !

In the case where `filtered_low` incorrectly contains values above `np.pi`, your fix would silently assign such values to the last bins, instead of raising an error.

I would prefer changing the bins into `phase_bins = np.linspace(-np.pi, np.pi + eps, n_bins + 1)`, with `eps = np.finfo(filtered_low.dtype).eps`.
What do you think ?

**Comment by alexrockhill** [comment]
I was thinking about that approach but wasn't sure if/how best to implement. Sounds good.

**Comment by alexrockhill** [comment]
Hmmm, this shifts all the bins slightly and didn't fix the issue. Perhaps `eps` is too small, looking into it.

**Comment by alexrockhill** [comment]
With `2 eps` it works.

**Comment by TomDLT** [comment]
Great thanks !

**Pull request merged**
